const NUMBER_OF_ROUNDS = 5;
const NUMBER_OF_PLAYERS = 1;
const NUMBER_OF_CRAPS = 10;
const NUMBER_OF_POINTS_TO_WIN = 30;
const POINTS_TABLE = [1,3,6, 10, 15, 21, 28, 36, 45, 55]


export {
  NUMBER_OF_ROUNDS,
  NUMBER_OF_PLAYERS,
  NUMBER_OF_CRAPS,
  NUMBER_OF_POINTS_TO_WIN,
  POINTS_TABLE
}